name       : iw
version    : 4.14
release    : 3
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/iw/iw-4.14.tar.xz : f01671c0074bfdec082a884057edba1b9efd35c89eda554638496f03b769ad89
license    : GPL-2.0-only
component  : network.base
summary    : nl80211 based CLI configuration utility for wireless devices
description: |
    nl80211 based CLI configuration utility for wireless devices
builddeps  :
    - pkgconfig(libnl-3.0)
build      : |
    %make
install    : |
    %make_install SBINDIR=/usr/bin
