name       : iw
version    : 4.1
release    : 1
source     :
    - https://www.kernel.org/pub/software/network/iw/iw-4.1.tar.xz : 5164aaacd8e82501d84a2187af194e8285a5a5b76e200447eb58d4dd78d1a34b
license    : GPL-2.0
summary    : nl80211 based CLI configuration utility for wireless devices
description: |
    nl80211 based CLI configuration utility for wireless devices
builddeps  :
    - pkgconfig(libnl-3.0)
build      : |
    %make
install    : |
    %make_install SBINDIR=/usr/bin
