name       : iw
version    : 5.0.1
release    : 5
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/iw/iw-5.0.1.tar.xz : 1e38ea794a223525b2ea7fe78fd14f2a56121e62e21ba5f9dbe8c494b35b5c0d
license    : GPL-2.0-only
component  : network.base
summary    : nl80211 based CLI configuration utility for wireless devices
description: |
    nl80211 based CLI configuration utility for wireless devices
builddeps  :
    - pkgconfig(libnl-3.0)
build      : |
    %make
install    : |
    %make_install SBINDIR=/usr/bin
